### ISSUE TITLE
Julia v1.9 - new q option does not quit

### ISSUE THREAD

**Issue by albheim** [giordano/PkgCleanup.jl#6]
Running the `PkgCleanup.manifests()` function we get a terminal menu.
Here the q option did not quit, but took me to the y/n prompt where I was close to answering y because _yes I want to quit_. What it was asking was if I wanted to delete all manifest references (all were chosen as default on start, and I didn't change any).

Feels like as it is now q (quit) and d (done) do exactly the same thing, which is a bit wasted, and at least in my opinion it is a bit unintuitive to get asked about deleting all after saying I want to quit.

**Comment by giordano** [comment]
```
julia> PkgCleanup.manifests()
Select the Manifest.toml to keep in /home/mose/.julia/logs/manifest_usage.toml
[press: d=done, a=all, n=none]
```
there's no quit option or am I missing something?

**Comment by albheim** [comment]
Seems like that is new for 1.9, getting the same as you on 1.8 but for me it looked like this:
```julia
julia> PkgCleanup.manifests()
Select the Manifest.toml to keep in /local/home/albheim/.julia/logs/manifest_usage.toml
[press: Enter=toggle, a=all, n=none, d=done, q=abort]
 > [X] /local/home/albheim/.julia/dev/ControlSystems/Manifest.toml
   [X] /local/home/albheim/.julia/dev/EMpht/Manifest.toml
   [X] /local/home/albheim/.julia/dev/PoleExploration/Manifest.toml
   [X] /local/home/albheim/.julia/dev/ReinforcementLearning/Manifest.toml
   [X] /local/home/albheim/.julia/environments/control/Manifest.toml
   [X] /local/home/albheim/.julia/environments/ml/Manifest.toml
   [X] /local/home/albheim/.julia/environments/v1.8/Manifest.toml
   [X] /local/home/albheim/.julia/environments/v1.9/Manifest.toml
   [X] /local/home/albheim/.julia/packages/Random123/qWUjl/Manifest.toml
v  [X] /local/home/albheim/Nextcloud/projects/ude_microservice_models/presentation/experiment/Manifest.toml
```

**Comment by giordano** [comment]
Well, the problem of the `q` option is that it returns an empty set, which isn't very useful as it's ***identical*** to the `n` (none) option.  There's no programmatic way to properly catch an actual quit.  That's an upstream limitation in REPL.TerminalMenus.  You may want to plug this into the brand-new issue https://github.com/JuliaLang/julia/issues/48381

**Comment by albheim** [comment]
Makes sense, I'll see if I add it there somewhere instead then. Closing this.
